-- ============================================================
-- FIORAVANTE APP — SETUP COMPLETO DO SCHEMA
-- Execute no SQL Editor do Supabase (projeto zvuxzrfbmmbhuhwaofrn)
-- ============================================================

-- 1. Criar schema isolado
CREATE SCHEMA IF NOT EXISTS fioravante;

-- 2. Tabela de professores autorizados
CREATE TABLE IF NOT EXISTS fioravante.authorized_professors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'professor',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabela de alunos
CREATE TABLE IF NOT EXISTS fioravante.students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome TEXT NOT NULL,
    ra TEXT NOT NULL,
    turma TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabela de ocorrencias
CREATE TABLE IF NOT EXISTS fioravante.incidents (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    data TEXT,
    professor TEXT,
    turma TEXT,
    aluno TEXT,
    ra TEXT,
    disciplina TEXT,
    irregularidades TEXT[],
    descricao TEXT,
    horario TEXT,
    status TEXT DEFAULT 'PENDENTE',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Habilitar RLS
ALTER TABLE fioravante.authorized_professors ENABLE ROW LEVEL SECURITY;
ALTER TABLE fioravante.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE fioravante.incidents ENABLE ROW LEVEL SECURITY;

-- 6. Politicas de acesso
DROP POLICY IF EXISTS "fioravante_professors_read" ON fioravante.authorized_professors;
CREATE POLICY "fioravante_professors_read"
  ON fioravante.authorized_professors FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "fioravante_students_all" ON fioravante.students;
CREATE POLICY "fioravante_students_all"
  ON fioravante.students FOR ALL
  TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "fioravante_incidents_insert" ON fioravante.incidents;
CREATE POLICY "fioravante_incidents_insert"
  ON fioravante.incidents FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "fioravante_incidents_select" ON fioravante.incidents;
CREATE POLICY "fioravante_incidents_select"
  ON fioravante.incidents FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "fioravante_incidents_update" ON fioravante.incidents;
CREATE POLICY "fioravante_incidents_update"
  ON fioravante.incidents FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);

-- 7. Expor schema fioravante via API REST do Supabase
-- IMPORTANTE: Acesse Dashboard > Settings > API > Extra schemas
-- e adicione "fioravante" na lista de schemas expostos

-- 8. Inserir todos os professores autorizados
INSERT INTO fioravante.authorized_professors (email, nome, role) VALUES
  -- GESTORES
  ('cadastroslkm@gmail.com', 'CADASTROS LKM - GESTAO', 'gestor'),
  ('vilera@prof.educacao.sp.gov.br', 'RAUL VILERA - GESTAO', 'gestor'),
  ('patricia.alexandre1@educacao.sp.gov.br', 'PATRICIA DE OLIVEIRA ALEXANDRE VILERA - GESTAO', 'gestor'),
  ('patricia.alexandre1@servidor.educacao.sp.gov.br', 'PATRICIA DE OLIVEIRA ALEXANDRE VILERA - GESTAO', 'gestor'),
  -- PROFESSORES
  ('alexandreos@professor.educacao.sp.gov.br', 'ALEXANDRE OLIVEIRA DOS SANTOS', 'professor'),
  ('alexandreos@prof.educacao.sp.gov.br', 'ALEXANDRE OLIVEIRA DOS SANTOS', 'professor'),
  ('anapolito@professor.educacao.sp.gov.br', 'ANA CAROLINA POLITO PINHEIRO', 'professor'),
  ('anapolito@prof.educacao.sp.gov.br', 'ANA CAROLINA POLITO PINHEIRO', 'professor'),
  ('anasantos51@professor.educacao.sp.gov.br', 'ANA PAULA DE SANTANA SANTOS', 'professor'),
  ('anasantos51@prof.educacao.sp.gov.br', 'ANA PAULA DE SANTANA SANTOS', 'professor'),
  ('anielisilva@professor.educacao.sp.gov.br', 'ANIELI SOFIA RODRIGUES DA SILVA', 'professor'),
  ('anielisilva@prof.educacao.sp.gov.br', 'ANIELI SOFIA RODRIGUES DA SILVA', 'professor'),
  ('brunanicole@professor.educacao.sp.gov.br', 'BRUNA NICOLE FERREIRA SANTOS', 'professor'),
  ('brunanicole@prof.educacao.sp.gov.br', 'BRUNA NICOLE FERREIRA SANTOS', 'professor'),
  ('camilacostamonteiro@professor.educacao.sp.gov.br', 'CAMILA COSTA MONTEIRO ROSSI', 'professor'),
  ('camilacostamonteiro@prof.educacao.sp.gov.br', 'CAMILA COSTA MONTEIRO ROSSI', 'professor'),
  ('carolinamduarte@professor.educacao.sp.gov.br', 'CAROLINA MARIA DUARTE', 'professor'),
  ('carolinamduarte@prof.educacao.sp.gov.br', 'CAROLINA MARIA DUARTE', 'professor'),
  ('cintiabernadete@professor.educacao.sp.gov.br', 'CINTIA BERNADETE FERRAZ MATAVELLI', 'professor'),
  ('cintiabernadete@prof.educacao.sp.gov.br', 'CINTIA BERNADETE FERRAZ MATAVELLI', 'professor'),
  ('clarinetesilva@professor.educacao.sp.gov.br', 'CLARINETE HELENA ALVES DA SILVA', 'professor'),
  ('clarinetesilva@prof.educacao.sp.gov.br', 'CLARINETE HELENA ALVES DA SILVA', 'professor'),
  ('denisesalvatierra@professor.educacao.sp.gov.br', 'DENISE SALVATIERRA ROMAO', 'professor'),
  ('denisesalvatierra@prof.educacao.sp.gov.br', 'DENISE SALVATIERRA ROMAO', 'professor'),
  ('edvaniabarros@professor.educacao.sp.gov.br', 'EDVANIA BEZERRA BARROS', 'professor'),
  ('edvaniabarros@prof.educacao.sp.gov.br', 'EDVANIA BEZERRA BARROS', 'professor'),
  ('ellenmeire@professor.educacao.sp.gov.br', 'ELLEN MEIRE MARIANO DE SOUSA REIS', 'professor'),
  ('ellenmeire@prof.educacao.sp.gov.br', 'ELLEN MEIRE MARIANO DE SOUSA REIS', 'professor'),
  ('giselesalviato@professor.educacao.sp.gov.br', 'GISELE SALVIATO CARNEIRO SINCIC', 'professor'),
  ('giselesalviato@prof.educacao.sp.gov.br', 'GISELE SALVIATO CARNEIRO SINCIC', 'professor'),
  ('gcabrera@professor.educacao.sp.gov.br', 'GISLENE CABRERA', 'professor'),
  ('gcabrera@prof.educacao.sp.gov.br', 'GISLENE CABRERA', 'professor'),
  ('iaravlima@professor.educacao.sp.gov.br', 'IARA VIEIRA LIMA', 'professor'),
  ('iaravlima@prof.educacao.sp.gov.br', 'IARA VIEIRA LIMA', 'professor'),
  ('itamaras@professor.educacao.sp.gov.br', 'ITAMARA SANTANA DE OLIVEIRA', 'professor'),
  ('itamaras@prof.educacao.sp.gov.br', 'ITAMARA SANTANA DE OLIVEIRA', 'professor'),
  ('janeteg@professor.educacao.sp.gov.br', 'JANETE GALDINO DOS SANTOS SOUZA', 'professor'),
  ('janeteg@prof.educacao.sp.gov.br', 'JANETE GALDINO DOS SANTOS SOUZA', 'professor'),
  ('jocelma@professor.educacao.sp.gov.br', 'JOCELMA FERREIRA DOS SANTOS', 'professor'),
  ('jocelma@prof.educacao.sp.gov.br', 'JOCELMA FERREIRA DOS SANTOS', 'professor'),
  ('joycemarilia@professor.educacao.sp.gov.br', 'JOYCE MARILIA DA SILVA DIAS', 'professor'),
  ('joycemarilia@prof.educacao.sp.gov.br', 'JOYCE MARILIA DA SILVA DIAS', 'professor'),
  ('lainechagas@professor.educacao.sp.gov.br', 'LAINE SA DE SOUZA CHAGAS', 'professor'),
  ('lainechagas@prof.educacao.sp.gov.br', 'LAINE SA DE SOUZA CHAGAS', 'professor'),
  ('luizvieiragomes@professor.educacao.sp.gov.br', 'LUIZ VIEIRA GOMES', 'professor'),
  ('luizvieiragomes@prof.educacao.sp.gov.br', 'LUIZ VIEIRA GOMES', 'professor'),
  ('marciasaturnino@professor.educacao.sp.gov.br', 'MARCIA BETIZ SATURNINO', 'professor'),
  ('marciasaturnino@prof.educacao.sp.gov.br', 'MARCIA BETIZ SATURNINO', 'professor'),
  ('marciagomez@professor.educacao.sp.gov.br', 'MARCIA RITA GOMEZ MALERBA', 'professor'),
  ('marciagomez@prof.educacao.sp.gov.br', 'MARCIA RITA GOMEZ MALERBA', 'professor'),
  ('isagomes@professor.educacao.sp.gov.br', 'MARIA ISABEL GOMES SANTANA FERNANDES', 'professor'),
  ('isagomes@prof.educacao.sp.gov.br', 'MARIA ISABEL GOMES SANTANA FERNANDES', 'professor'),
  ('marianaventura@professor.educacao.sp.gov.br', 'MARIANA CAROLINA BOA VENTURA', 'professor'),
  ('marianaventura@prof.educacao.sp.gov.br', 'MARIANA CAROLINA BOA VENTURA', 'professor'),
  ('rosilenesan@professor.educacao.sp.gov.br', 'ROSILENE SANTANA ALVES SILVA', 'professor'),
  ('rosilenesan@prof.educacao.sp.gov.br', 'ROSILENE SANTANA ALVES SILVA', 'professor'),
  ('rosirenel@professor.educacao.sp.gov.br', 'ROSIRENE LEME BERALDI GOTTARDI', 'professor'),
  ('rosirenel@prof.educacao.sp.gov.br', 'ROSIRENE LEME BERALDI GOTTARDI', 'professor'),
  ('vanessacatiane@professor.educacao.sp.gov.br', 'VANESSA CATIANE DA SILVA PORTO', 'professor'),
  ('vanessacatiane@prof.educacao.sp.gov.br', 'VANESSA CATIANE DA SILVA PORTO', 'professor'),
  ('vanessardantas@professor.educacao.sp.gov.br', 'VANESSA RODRIGUES DANTAS', 'professor'),
  ('vanessardantas@prof.educacao.sp.gov.br', 'VANESSA RODRIGUES DANTAS', 'professor')
ON CONFLICT (email) DO UPDATE SET nome = EXCLUDED.nome, role = EXCLUDED.role;

-- 9. Verificacao final
SELECT role, COUNT(*) as total FROM fioravante.authorized_professors GROUP BY role;
